// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: identity/app.proto

package identity

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AppService service

func NewAppServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "AppService.PageResources",
			Path:    []string{"/identity/app/page/resources"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		{
			Name:    "AppService.ApiResources",
			Path:    []string{"/identity/app/api/resources"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
	}
}

// Client API for AppService service

type AppService interface {
	Register(ctx context.Context, in *AppRegisterRequest, opts ...client.CallOption) (*AppRegisterResponse, error)
	PageResources(ctx context.Context, in *AppPageResourceRequest, opts ...client.CallOption) (*AppPageResourceResponse, error)
	ApiResources(ctx context.Context, in *AppApiResourceRequest, opts ...client.CallOption) (*AppApiResourceResponse, error)
}

type appService struct {
	c    client.Client
	name string
}

func NewAppService(name string, c client.Client) AppService {
	return &appService{
		c:    c,
		name: name,
	}
}

func (c *appService) Register(ctx context.Context, in *AppRegisterRequest, opts ...client.CallOption) (*AppRegisterResponse, error) {
	req := c.c.NewRequest(c.name, "AppService.Register", in)
	out := new(AppRegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appService) PageResources(ctx context.Context, in *AppPageResourceRequest, opts ...client.CallOption) (*AppPageResourceResponse, error) {
	req := c.c.NewRequest(c.name, "AppService.PageResources", in)
	out := new(AppPageResourceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appService) ApiResources(ctx context.Context, in *AppApiResourceRequest, opts ...client.CallOption) (*AppApiResourceResponse, error) {
	req := c.c.NewRequest(c.name, "AppService.ApiResources", in)
	out := new(AppApiResourceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AppService service

type AppServiceHandler interface {
	Register(context.Context, *AppRegisterRequest, *AppRegisterResponse) error
	PageResources(context.Context, *AppPageResourceRequest, *AppPageResourceResponse) error
	ApiResources(context.Context, *AppApiResourceRequest, *AppApiResourceResponse) error
}

func MicroRegisterAppServiceHandler(s server.Server, hdlr AppServiceHandler, opts ...server.HandlerOption) error {
	type appService interface {
		Register(ctx context.Context, in *AppRegisterRequest, out *AppRegisterResponse) error
		PageResources(ctx context.Context, in *AppPageResourceRequest, out *AppPageResourceResponse) error
		ApiResources(ctx context.Context, in *AppApiResourceRequest, out *AppApiResourceResponse) error
	}
	type AppService struct {
		appService
	}
	h := &appServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "AppService.PageResources",
		Path:    []string{"/identity/app/page/resources"},
		Method:  []string{"GET"},
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "AppService.ApiResources",
		Path:    []string{"/identity/app/api/resources"},
		Method:  []string{"GET"},
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&AppService{h}, opts...))
}

type appServiceHandler struct {
	AppServiceHandler
}

func (h *appServiceHandler) Register(ctx context.Context, in *AppRegisterRequest, out *AppRegisterResponse) error {
	return h.AppServiceHandler.Register(ctx, in, out)
}

func (h *appServiceHandler) PageResources(ctx context.Context, in *AppPageResourceRequest, out *AppPageResourceResponse) error {
	return h.AppServiceHandler.PageResources(ctx, in, out)
}

func (h *appServiceHandler) ApiResources(ctx context.Context, in *AppApiResourceRequest, out *AppApiResourceResponse) error {
	return h.AppServiceHandler.ApiResources(ctx, in, out)
}
