// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: identity/permission.proto

package identity

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CRUD
type PermCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *PermCreateRequest) Reset() {
	*x = PermCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermCreateRequest) ProtoMessage() {}

func (x *PermCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermCreateRequest.ProtoReflect.Descriptor instead.
func (*PermCreateRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{0}
}

func (x *PermCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PermCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PermCreateResponse) Reset() {
	*x = PermCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermCreateResponse) ProtoMessage() {}

func (x *PermCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermCreateResponse.ProtoReflect.Descriptor instead.
func (*PermCreateResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{1}
}

type PermReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PermReadRequest) Reset() {
	*x = PermReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermReadRequest) ProtoMessage() {}

func (x *PermReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermReadRequest.ProtoReflect.Descriptor instead.
func (*PermReadRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{2}
}

func (x *PermReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PermReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *PermReadResponse) Reset() {
	*x = PermReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermReadResponse) ProtoMessage() {}

func (x *PermReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermReadResponse.ProtoReflect.Descriptor instead.
func (*PermReadResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{3}
}

func (x *PermReadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermReadResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermReadResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PermUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *PermUpdateRequest) Reset() {
	*x = PermUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermUpdateRequest) ProtoMessage() {}

func (x *PermUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermUpdateRequest.ProtoReflect.Descriptor instead.
func (*PermUpdateRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{4}
}

func (x *PermUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PermUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PermUpdateResponse) Reset() {
	*x = PermUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermUpdateResponse) ProtoMessage() {}

func (x *PermUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermUpdateResponse.ProtoReflect.Descriptor instead.
func (*PermUpdateResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{5}
}

type PermDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PermDeleteRequest) Reset() {
	*x = PermDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermDeleteRequest) ProtoMessage() {}

func (x *PermDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermDeleteRequest.ProtoReflect.Descriptor instead.
func (*PermDeleteRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{6}
}

func (x *PermDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PermDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PermDeleteResponse) Reset() {
	*x = PermDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermDeleteResponse) ProtoMessage() {}

func (x *PermDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermDeleteResponse.ProtoReflect.Descriptor instead.
func (*PermDeleteResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{7}
}

type PermListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PermListRequest) Reset() {
	*x = PermListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermListRequest) ProtoMessage() {}

func (x *PermListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermListRequest.ProtoReflect.Descriptor instead.
func (*PermListRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{8}
}

type PermListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permissions []*PermReadResponse `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *PermListResponse) Reset() {
	*x = PermListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermListResponse) ProtoMessage() {}

func (x *PermListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermListResponse.ProtoReflect.Descriptor instead.
func (*PermListResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{9}
}

func (x *PermListResponse) GetPermissions() []*PermReadResponse {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// page resource
type PermPageResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PermPageResourceRequest) Reset() {
	*x = PermPageResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermPageResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermPageResourceRequest) ProtoMessage() {}

func (x *PermPageResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermPageResourceRequest.ProtoReflect.Descriptor instead.
func (*PermPageResourceRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{10}
}

func (x *PermPageResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PermPageResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path        string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Readonly    bool   `protobuf:"varint,5,opt,name=readonly,proto3" json:"readonly,omitempty"`
}

func (x *PermPageResource) Reset() {
	*x = PermPageResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermPageResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermPageResource) ProtoMessage() {}

func (x *PermPageResource) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermPageResource.ProtoReflect.Descriptor instead.
func (*PermPageResource) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{11}
}

func (x *PermPageResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermPageResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermPageResource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PermPageResource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PermPageResource) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

type PermPageResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources []*PermPageResource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *PermPageResourceResponse) Reset() {
	*x = PermPageResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermPageResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermPageResourceResponse) ProtoMessage() {}

func (x *PermPageResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermPageResourceResponse.ProtoReflect.Descriptor instead.
func (*PermPageResourceResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{12}
}

func (x *PermPageResourceResponse) GetResources() []*PermPageResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type PermGrantPageResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PageResourceIds []string `protobuf:"bytes,2,rep,name=pageResourceIds,proto3" json:"pageResourceIds,omitempty"`
}

func (x *PermGrantPageResourceRequest) Reset() {
	*x = PermGrantPageResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermGrantPageResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermGrantPageResourceRequest) ProtoMessage() {}

func (x *PermGrantPageResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermGrantPageResourceRequest.ProtoReflect.Descriptor instead.
func (*PermGrantPageResourceRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{13}
}

func (x *PermGrantPageResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermGrantPageResourceRequest) GetPageResourceIds() []string {
	if x != nil {
		return x.PageResourceIds
	}
	return nil
}

type PermGrantPageResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PermGrantPageResourceResponse) Reset() {
	*x = PermGrantPageResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermGrantPageResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermGrantPageResourceResponse) ProtoMessage() {}

func (x *PermGrantPageResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermGrantPageResourceResponse.ProtoReflect.Descriptor instead.
func (*PermGrantPageResourceResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{14}
}

type PermDeletePageResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PermId string `protobuf:"bytes,1,opt,name=permId,proto3" json:"permId,omitempty"`
	PageId string `protobuf:"bytes,2,opt,name=pageId,proto3" json:"pageId,omitempty"`
}

func (x *PermDeletePageResourceRequest) Reset() {
	*x = PermDeletePageResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermDeletePageResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermDeletePageResourceRequest) ProtoMessage() {}

func (x *PermDeletePageResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermDeletePageResourceRequest.ProtoReflect.Descriptor instead.
func (*PermDeletePageResourceRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{15}
}

func (x *PermDeletePageResourceRequest) GetPermId() string {
	if x != nil {
		return x.PermId
	}
	return ""
}

func (x *PermDeletePageResourceRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type PermDeletePageResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PermDeletePageResourceResponse) Reset() {
	*x = PermDeletePageResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermDeletePageResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermDeletePageResourceResponse) ProtoMessage() {}

func (x *PermDeletePageResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermDeletePageResourceResponse.ProtoReflect.Descriptor instead.
func (*PermDeletePageResourceResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{16}
}

// api resource
type PermApiResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PermApiResourceRequest) Reset() {
	*x = PermApiResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermApiResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermApiResourceRequest) ProtoMessage() {}

func (x *PermApiResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermApiResourceRequest.ProtoReflect.Descriptor instead.
func (*PermApiResourceRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{17}
}

func (x *PermApiResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PermApiResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GrpcMethod  string   `protobuf:"bytes,3,opt,name=grpcMethod,proto3" json:"grpcMethod,omitempty"`
	HttpPath    string   `protobuf:"bytes,4,opt,name=httpPath,proto3" json:"httpPath,omitempty"`
	Type        ApiTypes `protobuf:"varint,5,opt,name=type,proto3,enum=identity.ApiTypes" json:"type,omitempty"`
	Description string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Readonly    bool     `protobuf:"varint,7,opt,name=readonly,proto3" json:"readonly,omitempty"`
}

func (x *PermApiResource) Reset() {
	*x = PermApiResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermApiResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermApiResource) ProtoMessage() {}

func (x *PermApiResource) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermApiResource.ProtoReflect.Descriptor instead.
func (*PermApiResource) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{18}
}

func (x *PermApiResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermApiResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermApiResource) GetGrpcMethod() string {
	if x != nil {
		return x.GrpcMethod
	}
	return ""
}

func (x *PermApiResource) GetHttpPath() string {
	if x != nil {
		return x.HttpPath
	}
	return ""
}

func (x *PermApiResource) GetType() ApiTypes {
	if x != nil {
		return x.Type
	}
	return ApiTypes_HTTP
}

func (x *PermApiResource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PermApiResource) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

type PermApiResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources []*PermApiResource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *PermApiResourceResponse) Reset() {
	*x = PermApiResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermApiResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermApiResourceResponse) ProtoMessage() {}

func (x *PermApiResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermApiResourceResponse.ProtoReflect.Descriptor instead.
func (*PermApiResourceResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{19}
}

func (x *PermApiResourceResponse) GetResources() []*PermApiResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type PermGrantApiResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApiResourceIds []string `protobuf:"bytes,2,rep,name=apiResourceIds,proto3" json:"apiResourceIds,omitempty"`
}

func (x *PermGrantApiResourceRequest) Reset() {
	*x = PermGrantApiResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermGrantApiResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermGrantApiResourceRequest) ProtoMessage() {}

func (x *PermGrantApiResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermGrantApiResourceRequest.ProtoReflect.Descriptor instead.
func (*PermGrantApiResourceRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{20}
}

func (x *PermGrantApiResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermGrantApiResourceRequest) GetApiResourceIds() []string {
	if x != nil {
		return x.ApiResourceIds
	}
	return nil
}

type PermGrantApiResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PermGrantApiResourceResponse) Reset() {
	*x = PermGrantApiResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermGrantApiResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermGrantApiResourceResponse) ProtoMessage() {}

func (x *PermGrantApiResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermGrantApiResourceResponse.ProtoReflect.Descriptor instead.
func (*PermGrantApiResourceResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{21}
}

type PermDeleteApiResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PermId string `protobuf:"bytes,1,opt,name=permId,proto3" json:"permId,omitempty"`
	ApiId  string `protobuf:"bytes,2,opt,name=apiId,proto3" json:"apiId,omitempty"`
}

func (x *PermDeleteApiResourceRequest) Reset() {
	*x = PermDeleteApiResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermDeleteApiResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermDeleteApiResourceRequest) ProtoMessage() {}

func (x *PermDeleteApiResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermDeleteApiResourceRequest.ProtoReflect.Descriptor instead.
func (*PermDeleteApiResourceRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{22}
}

func (x *PermDeleteApiResourceRequest) GetPermId() string {
	if x != nil {
		return x.PermId
	}
	return ""
}

func (x *PermDeleteApiResourceRequest) GetApiId() string {
	if x != nil {
		return x.ApiId
	}
	return ""
}

type PermDeleteApiResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PermDeleteApiResourceResponse) Reset() {
	*x = PermDeleteApiResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermDeleteApiResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermDeleteApiResourceResponse) ProtoMessage() {}

func (x *PermDeleteApiResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermDeleteApiResourceResponse.ProtoReflect.Descriptor instead.
func (*PermDeleteApiResourceResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{23}
}

// menu resource
type PermMenuResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PermMenuResourceRequest) Reset() {
	*x = PermMenuResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermMenuResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermMenuResourceRequest) ProtoMessage() {}

func (x *PermMenuResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermMenuResourceRequest.ProtoReflect.Descriptor instead.
func (*PermMenuResourceRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{24}
}

func (x *PermMenuResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PermMenuPageResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Resource *AppPageResource        `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Children []*PermMenuPageResource `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *PermMenuPageResource) Reset() {
	*x = PermMenuPageResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermMenuPageResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermMenuPageResource) ProtoMessage() {}

func (x *PermMenuPageResource) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermMenuPageResource.ProtoReflect.Descriptor instead.
func (*PermMenuPageResource) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{25}
}

func (x *PermMenuPageResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermMenuPageResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermMenuPageResource) GetResource() *AppPageResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *PermMenuPageResource) GetChildren() []*PermMenuPageResource {
	if x != nil {
		return x.Children
	}
	return nil
}

type PermMenuResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources *PermMenuPageResource `protobuf:"bytes,1,opt,name=resources,proto3" json:"resources,omitempty"`
}

func (x *PermMenuResourceResponse) Reset() {
	*x = PermMenuResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermMenuResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermMenuResourceResponse) ProtoMessage() {}

func (x *PermMenuResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermMenuResourceResponse.ProtoReflect.Descriptor instead.
func (*PermMenuResourceResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{26}
}

func (x *PermMenuResourceResponse) GetResources() *PermMenuPageResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type PermGrantMenuResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PermId       string   `protobuf:"bytes,2,opt,name=permId,proto3" json:"permId,omitempty"`
	PageId       string   `protobuf:"bytes,3,opt,name=pageId,proto3" json:"pageId,omitempty"`
	ParentId     string   `protobuf:"bytes,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	PageElements []string `protobuf:"bytes,5,rep,name=pageElements,proto3" json:"pageElements,omitempty"`
}

func (x *PermGrantMenuResourceRequest) Reset() {
	*x = PermGrantMenuResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermGrantMenuResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermGrantMenuResourceRequest) ProtoMessage() {}

func (x *PermGrantMenuResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermGrantMenuResourceRequest.ProtoReflect.Descriptor instead.
func (*PermGrantMenuResourceRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{27}
}

func (x *PermGrantMenuResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermGrantMenuResourceRequest) GetPermId() string {
	if x != nil {
		return x.PermId
	}
	return ""
}

func (x *PermGrantMenuResourceRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *PermGrantMenuResourceRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *PermGrantMenuResourceRequest) GetPageElements() []string {
	if x != nil {
		return x.PageElements
	}
	return nil
}

type PermGrantMenuResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PermGrantMenuResourceResponse) Reset() {
	*x = PermGrantMenuResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermGrantMenuResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermGrantMenuResourceResponse) ProtoMessage() {}

func (x *PermGrantMenuResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermGrantMenuResourceResponse.ProtoReflect.Descriptor instead.
func (*PermGrantMenuResourceResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{28}
}

type PermDeleteMenuResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PermId string `protobuf:"bytes,1,opt,name=permId,proto3" json:"permId,omitempty"`
	MenuId string `protobuf:"bytes,2,opt,name=menuId,proto3" json:"menuId,omitempty"`
}

func (x *PermDeleteMenuResourceRequest) Reset() {
	*x = PermDeleteMenuResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermDeleteMenuResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermDeleteMenuResourceRequest) ProtoMessage() {}

func (x *PermDeleteMenuResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermDeleteMenuResourceRequest.ProtoReflect.Descriptor instead.
func (*PermDeleteMenuResourceRequest) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{29}
}

func (x *PermDeleteMenuResourceRequest) GetPermId() string {
	if x != nil {
		return x.PermId
	}
	return ""
}

func (x *PermDeleteMenuResourceRequest) GetMenuId() string {
	if x != nil {
		return x.MenuId
	}
	return ""
}

type PermDeleteMenuResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PermDeleteMenuResourceResponse) Reset() {
	*x = PermDeleteMenuResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_permission_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermDeleteMenuResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermDeleteMenuResourceResponse) ProtoMessage() {}

func (x *PermDeleteMenuResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_permission_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermDeleteMenuResourceResponse.ProtoReflect.Descriptor instead.
func (*PermDeleteMenuResourceResponse) Descriptor() ([]byte, []int) {
	return file_identity_permission_proto_rawDescGZIP(), []int{30}
}

var File_identity_permission_proto protoreflect.FileDescriptor

var file_identity_permission_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x61, 0x70,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x6d, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x50, 0x65, 0x72, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x50, 0x65, 0x72, 0x6d,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x58, 0x0a, 0x10, 0x50,
	0x65, 0x72, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x59, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x6d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x14, 0x0a, 0x12, 0x50, 0x65, 0x72, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x6d, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x50,
	0x65, 0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x11, 0x0a, 0x0f, 0x50, 0x65, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x10, 0x50, 0x65, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x29, 0x0a, 0x17, 0x50, 0x65, 0x72, 0x6d, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x88, 0x01, 0x0a, 0x10, 0x50, 0x65, 0x72, 0x6d, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x22, 0x54, 0x0a, 0x18,
	0x50, 0x65, 0x72, 0x6d, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x50, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x22, 0x58, 0x0a, 0x1c, 0x50, 0x65, 0x72, 0x6d, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x73, 0x22, 0x1f, 0x0a, 0x1d,
	0x50, 0x65, 0x72, 0x6d, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4f, 0x0a,
	0x1d, 0x50, 0x65, 0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x20,
	0x0a, 0x1e, 0x50, 0x65, 0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x28, 0x0a, 0x16, 0x50, 0x65, 0x72, 0x6d, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xd7, 0x01, 0x0a, 0x0f, 0x50,
	0x65, 0x72, 0x6d, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x74, 0x74, 0x70, 0x50, 0x61, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x74, 0x74, 0x70, 0x50, 0x61, 0x74, 0x68, 0x12, 0x26,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x41, 0x70, 0x69, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64,
	0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64,
	0x6f, 0x6e, 0x6c, 0x79, 0x22, 0x52, 0x0a, 0x17, 0x50, 0x65, 0x72, 0x6d, 0x41, 0x70, 0x69, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x37, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65,
	0x72, 0x6d, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x55, 0x0a, 0x1b, 0x50, 0x65, 0x72, 0x6d,
	0x47, 0x72, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0e, 0x61, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x73, 0x22,
	0x1e, 0x0a, 0x1c, 0x50, 0x65, 0x72, 0x6d, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x4c, 0x0a, 0x1c, 0x50, 0x65, 0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x69,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x69, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x69, 0x49, 0x64, 0x22, 0x1f, 0x0a,
	0x1d, 0x50, 0x65, 0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x69, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x29,
	0x0a, 0x17, 0x50, 0x65, 0x72, 0x6d, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xad, 0x01, 0x0a, 0x14, 0x50, 0x65,
	0x72, 0x6d, 0x4d, 0x65, 0x6e, 0x75, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x41, 0x70, 0x70, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x3a, 0x0a,
	0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x4d,
	0x65, 0x6e, 0x75, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x22, 0x58, 0x0a, 0x18, 0x50, 0x65, 0x72,
	0x6d, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x4d, 0x65, 0x6e, 0x75, 0x50, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x1c, 0x50, 0x65, 0x72, 0x6d, 0x47, 0x72, 0x61, 0x6e,
	0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x6d,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61, 0x67, 0x65, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x67, 0x65,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x1f, 0x0a, 0x1d, 0x50, 0x65, 0x72, 0x6d,
	0x47, 0x72, 0x61, 0x6e, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4f, 0x0a, 0x1d, 0x50, 0x65, 0x72,
	0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65,
	0x72, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x72, 0x6d,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x1e, 0x50, 0x65,
	0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xee, 0x0e, 0x0a,
	0x11, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x64, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x3a,
	0x01, 0x2a, 0x22, 0x14, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x60, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64,
	0x12, 0x19, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x12,
	0x19, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x69, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72,
	0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x1a, 0x19, 0x2f, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x66, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x1b, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1b, 0x2a, 0x19, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x5c, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x50, 0x65, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x88, 0x01, 0x0a, 0x0d,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x21, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2a, 0x12, 0x28, 0x2f, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x99, 0x01, 0x0a, 0x12, 0x47, 0x72, 0x61, 0x6e, 0x74,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x26, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x47, 0x72, 0x61,
	0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x50, 0x65, 0x72, 0x6d, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x32,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2c, 0x3a, 0x01, 0x2a, 0x1a, 0x27, 0x2f, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f,
	0x7b, 0x69, 0x64, 0x7d, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0xa5, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x27, 0x2e, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x28, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65,
	0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3c, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x36, 0x2a, 0x34, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x7b, 0x70, 0x65, 0x72, 0x6d,
	0x49, 0x64, 0x7d, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x7b, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x7d, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x84, 0x01, 0x0a, 0x0c, 0x41,
	0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x41, 0x70, 0x69, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x41, 0x70, 0x69,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x29, 0x12, 0x27, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x12, 0x95, 0x01, 0x0a, 0x11, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x25, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x47, 0x72,
	0x61, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x31, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2b, 0x3a, 0x01,
	0x2a, 0x1a, 0x26, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0xa0, 0x01, 0x0a, 0x11, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x26, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x69,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x3a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x34, 0x2a, 0x32, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x7b,
	0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x7d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x7b, 0x61, 0x70, 0x69,
	0x49, 0x64, 0x7d, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x87, 0x01, 0x0a,
	0x0d, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x21,
	0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x4d, 0x65,
	0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72,
	0x6d, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2a, 0x12, 0x28, 0x2f, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x9c, 0x01, 0x0a, 0x11, 0x47, 0x72, 0x61, 0x6e, 0x74,
	0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x26, 0x2e, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x47, 0x72, 0x61, 0x6e,
	0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x36, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x30, 0x3a, 0x01, 0x2a, 0x1a, 0x2b, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x7b,
	0x70, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x7d, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0xa5, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x27, 0x2e, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x50, 0x65, 0x72, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x3c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x36, 0x2a, 0x34, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x7b, 0x70,
	0x65, 0x72, 0x6d, 0x49, 0x64, 0x7d, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2f, 0x7b, 0x6d, 0x65, 0x6e,
	0x75, 0x49, 0x64, 0x7d, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x0d, 0x5a,
	0x0b, 0x2e, 0x2f, 0x3b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_identity_permission_proto_rawDescOnce sync.Once
	file_identity_permission_proto_rawDescData = file_identity_permission_proto_rawDesc
)

func file_identity_permission_proto_rawDescGZIP() []byte {
	file_identity_permission_proto_rawDescOnce.Do(func() {
		file_identity_permission_proto_rawDescData = protoimpl.X.CompressGZIP(file_identity_permission_proto_rawDescData)
	})
	return file_identity_permission_proto_rawDescData
}

var file_identity_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_identity_permission_proto_goTypes = []interface{}{
	(*PermCreateRequest)(nil),              // 0: identity.PermCreateRequest
	(*PermCreateResponse)(nil),             // 1: identity.PermCreateResponse
	(*PermReadRequest)(nil),                // 2: identity.PermReadRequest
	(*PermReadResponse)(nil),               // 3: identity.PermReadResponse
	(*PermUpdateRequest)(nil),              // 4: identity.PermUpdateRequest
	(*PermUpdateResponse)(nil),             // 5: identity.PermUpdateResponse
	(*PermDeleteRequest)(nil),              // 6: identity.PermDeleteRequest
	(*PermDeleteResponse)(nil),             // 7: identity.PermDeleteResponse
	(*PermListRequest)(nil),                // 8: identity.PermListRequest
	(*PermListResponse)(nil),               // 9: identity.PermListResponse
	(*PermPageResourceRequest)(nil),        // 10: identity.PermPageResourceRequest
	(*PermPageResource)(nil),               // 11: identity.PermPageResource
	(*PermPageResourceResponse)(nil),       // 12: identity.PermPageResourceResponse
	(*PermGrantPageResourceRequest)(nil),   // 13: identity.PermGrantPageResourceRequest
	(*PermGrantPageResourceResponse)(nil),  // 14: identity.PermGrantPageResourceResponse
	(*PermDeletePageResourceRequest)(nil),  // 15: identity.PermDeletePageResourceRequest
	(*PermDeletePageResourceResponse)(nil), // 16: identity.PermDeletePageResourceResponse
	(*PermApiResourceRequest)(nil),         // 17: identity.PermApiResourceRequest
	(*PermApiResource)(nil),                // 18: identity.PermApiResource
	(*PermApiResourceResponse)(nil),        // 19: identity.PermApiResourceResponse
	(*PermGrantApiResourceRequest)(nil),    // 20: identity.PermGrantApiResourceRequest
	(*PermGrantApiResourceResponse)(nil),   // 21: identity.PermGrantApiResourceResponse
	(*PermDeleteApiResourceRequest)(nil),   // 22: identity.PermDeleteApiResourceRequest
	(*PermDeleteApiResourceResponse)(nil),  // 23: identity.PermDeleteApiResourceResponse
	(*PermMenuResourceRequest)(nil),        // 24: identity.PermMenuResourceRequest
	(*PermMenuPageResource)(nil),           // 25: identity.PermMenuPageResource
	(*PermMenuResourceResponse)(nil),       // 26: identity.PermMenuResourceResponse
	(*PermGrantMenuResourceRequest)(nil),   // 27: identity.PermGrantMenuResourceRequest
	(*PermGrantMenuResourceResponse)(nil),  // 28: identity.PermGrantMenuResourceResponse
	(*PermDeleteMenuResourceRequest)(nil),  // 29: identity.PermDeleteMenuResourceRequest
	(*PermDeleteMenuResourceResponse)(nil), // 30: identity.PermDeleteMenuResourceResponse
	(ApiTypes)(0),                          // 31: identity.ApiTypes
	(*AppPageResource)(nil),                // 32: identity.AppPageResource
}
var file_identity_permission_proto_depIdxs = []int32{
	3,  // 0: identity.PermListResponse.permissions:type_name -> identity.PermReadResponse
	11, // 1: identity.PermPageResourceResponse.resources:type_name -> identity.PermPageResource
	31, // 2: identity.PermApiResource.type:type_name -> identity.ApiTypes
	18, // 3: identity.PermApiResourceResponse.resources:type_name -> identity.PermApiResource
	32, // 4: identity.PermMenuPageResource.resource:type_name -> identity.AppPageResource
	25, // 5: identity.PermMenuPageResource.children:type_name -> identity.PermMenuPageResource
	25, // 6: identity.PermMenuResourceResponse.resources:type_name -> identity.PermMenuPageResource
	0,  // 7: identity.PermissionService.Create:input_type -> identity.PermCreateRequest
	2,  // 8: identity.PermissionService.Read:input_type -> identity.PermReadRequest
	4,  // 9: identity.PermissionService.Update:input_type -> identity.PermUpdateRequest
	6,  // 10: identity.PermissionService.Delete:input_type -> identity.PermDeleteRequest
	8,  // 11: identity.PermissionService.List:input_type -> identity.PermListRequest
	10, // 12: identity.PermissionService.PageResources:input_type -> identity.PermPageResourceRequest
	13, // 13: identity.PermissionService.GrantPageResources:input_type -> identity.PermGrantPageResourceRequest
	15, // 14: identity.PermissionService.DeletePageResource:input_type -> identity.PermDeletePageResourceRequest
	17, // 15: identity.PermissionService.ApiResources:input_type -> identity.PermApiResourceRequest
	20, // 16: identity.PermissionService.GrantApiResources:input_type -> identity.PermGrantApiResourceRequest
	22, // 17: identity.PermissionService.DeleteApiResource:input_type -> identity.PermDeleteApiResourceRequest
	24, // 18: identity.PermissionService.MenuResources:input_type -> identity.PermMenuResourceRequest
	27, // 19: identity.PermissionService.GrantMenuResource:input_type -> identity.PermGrantMenuResourceRequest
	29, // 20: identity.PermissionService.DeleteMenuResource:input_type -> identity.PermDeleteMenuResourceRequest
	1,  // 21: identity.PermissionService.Create:output_type -> identity.PermCreateResponse
	3,  // 22: identity.PermissionService.Read:output_type -> identity.PermReadResponse
	5,  // 23: identity.PermissionService.Update:output_type -> identity.PermUpdateResponse
	7,  // 24: identity.PermissionService.Delete:output_type -> identity.PermDeleteResponse
	9,  // 25: identity.PermissionService.List:output_type -> identity.PermListResponse
	12, // 26: identity.PermissionService.PageResources:output_type -> identity.PermPageResourceResponse
	14, // 27: identity.PermissionService.GrantPageResources:output_type -> identity.PermGrantPageResourceResponse
	16, // 28: identity.PermissionService.DeletePageResource:output_type -> identity.PermDeletePageResourceResponse
	19, // 29: identity.PermissionService.ApiResources:output_type -> identity.PermApiResourceResponse
	21, // 30: identity.PermissionService.GrantApiResources:output_type -> identity.PermGrantApiResourceResponse
	23, // 31: identity.PermissionService.DeleteApiResource:output_type -> identity.PermDeleteApiResourceResponse
	24, // 32: identity.PermissionService.MenuResources:output_type -> identity.PermMenuResourceRequest
	28, // 33: identity.PermissionService.GrantMenuResource:output_type -> identity.PermGrantMenuResourceResponse
	30, // 34: identity.PermissionService.DeleteMenuResource:output_type -> identity.PermDeleteMenuResourceResponse
	21, // [21:35] is the sub-list for method output_type
	7,  // [7:21] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_identity_permission_proto_init() }
func file_identity_permission_proto_init() {
	if File_identity_permission_proto != nil {
		return
	}
	file_identity_app_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_identity_permission_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermPageResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermPageResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermPageResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermGrantPageResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermGrantPageResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermDeletePageResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermDeletePageResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermApiResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermApiResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermApiResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermGrantApiResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermGrantApiResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermDeleteApiResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermDeleteApiResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermMenuResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermMenuPageResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermMenuResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermGrantMenuResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermGrantMenuResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermDeleteMenuResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_permission_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermDeleteMenuResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_identity_permission_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_permission_proto_goTypes,
		DependencyIndexes: file_identity_permission_proto_depIdxs,
		MessageInfos:      file_identity_permission_proto_msgTypes,
	}.Build()
	File_identity_permission_proto = out.File
	file_identity_permission_proto_rawDesc = nil
	file_identity_permission_proto_goTypes = nil
	file_identity_permission_proto_depIdxs = nil
}
